// Generated by https://quicktype.io

export interface GetProductRes {
  ok: boolean;
  msg: string;
  products: Product[];
}

export interface Product {
  name: string;
  description: string;
  quantity: number;
  price: number;
  urlImage: string;
  userId: string;
  id: string;
}
