// Generated by https://quicktype.io

export interface UpdatedProductRes {
  ok: boolean;
  msg: string;
  updatedProduct: UpdatedProduct;
}

export interface UpdatedProduct {
  name: string;
  description: string;
  quantity: number;
  price: number;
  urlImage: string;
  userId: string;
  id: string;
}
